/**
 * UNTITLED STUDIO - FILM PRESETS LIBRARY
 * 150+ professional film stock emulations
 * REORGANIZED: Big Brands, Vintage, Obscure, & Styles
 */

const FilmPresets = {
    // ============ KODAK ============
    kodak: [
        {
            name: "Portra 400",
            category: "kodak",
            exposure: 0.05,
            contrast: -5,
            highlights: -10,
            shadows: 15,
            whites: -5,
            blacks: 5,
            temperature: 5,
            tint: 2,
            vibrance: -10,
            saturation: -5,
            grain: 8,
            grainGlobal: 1,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 1.2,
            fade: 5
        },
        {
            name: "Vision3 250D",
            category: "kodak",
            exposure: 0.05,
            contrast: -5,
            highlights: -20,
            shadows: 10,
            whites: -15,
            blacks: 2,
            temperature: 2,
            tint: 0,
            vibrance: -5,
            saturation: 5,
            grain: 10,
            grainGlobal: 1,
            bloomStrength: 30,
            bloomThreshold: 50,
            grainSize: 1.1,
            fade: 2,
            halation: 0.3
        },
        {
            name: "Portra 160",
            category: "kodak",
            exposure: 0.03,
            contrast: -8,
            highlights: -15,
            shadows: 10,
            whites: -8,
            blacks: 3,
            temperature: 3,
            tint: 0,
            vibrance: -15,
            saturation: -8,
            grain: 5,
            grainGlobal: 0.9,
            bloomStrength: 10,
            bloomThreshold: 65,
            grainSize: 1,
            fade: 3
        },
        {
            name: "Portra 800",
            category: "kodak",
            exposure: 0.08,
            contrast: -3,
            highlights: -5,
            shadows: 20,
            whites: -3,
            blacks: 8,
            temperature: 8,
            tint: 3,
            vibrance: -8,
            saturation: -3,
            grain: 15,
            grainGlobal: 1.2,
            bloomStrength: 25,
            bloomThreshold: 50,
            grainSize: 1.5,
            fade: 8
        },
        {
            name: "Ektar 100",
            category: "kodak",
            exposure: 0,
            contrast: 15,
            highlights: -5,
            shadows: -10,
            whites: 5,
            blacks: -5,
            temperature: -5,
            tint: 5,
            vibrance: 20,
            saturation: 15,
            grain: 3,
            grainGlobal: 0.8,
            bloomStrength: 5,
            bloomThreshold: 80,
            grainSize: 0.8,
            fade: 0
        },
        {
            name: "Gold 200",
            category: "kodak",
            exposure: 0.1,
            contrast: 5,
            highlights: 5,
            shadows: 10,
            whites: 8,
            blacks: 5,
            temperature: 15,
            tint: 5,
            vibrance: 10,
            saturation: 8,
            grain: 12,
            grainGlobal: 1,
            bloomStrength: 20,
            bloomThreshold: 55,
            grainSize: 1.3,
            fade: 5
        },
        {
            name: "ColorPlus 200",
            category: "kodak",
            exposure: 0.05,
            contrast: 10,
            highlights: 0,
            shadows: 5,
            whites: 5,
            blacks: 0,
            temperature: 10,
            tint: 3,
            vibrance: 5,
            saturation: 5,
            grain: 10,
            grainGlobal: 1,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 1.2,
            fade: 3
        },
        {
            name: "Ultramax 400",
            category: "kodak",
            exposure: 0.08,
            contrast: 8,
            highlights: 5,
            shadows: 8,
            whites: 5,
            blacks: 3,
            temperature: 12,
            tint: 5,
            vibrance: 12,
            saturation: 10,
            grain: 15,
            grainGlobal: 1.2,
            bloomStrength: 20,
            bloomThreshold: 55,
            grainSize: 1.4,
            fade: 5
        },
        {
            name: "Pro Image 100",
            category: "kodak",
            exposure: 0,
            contrast: 5,
            highlights: -5,
            shadows: 5,
            whites: 0,
            blacks: 0,
            temperature: 5,
            tint: 0,
            vibrance: 0,
            saturation: 5,
            grain: 5,
            grainGlobal: 0.9,
            bloomStrength: 8,
            bloomThreshold: 70,
            grainSize: 0.9,
            fade: 0
        },
        {
            name: "Vision3 500T",
            category: "kodak",
            exposure: 0.05,
            contrast: 10,
            highlights: -8,
            shadows: 5,
            whites: 0,
            blacks: 5,
            temperature: -15,
            tint: 5,
            vibrance: 5,
            saturation: 0,
            grain: 8,
            grainGlobal: 1,
            bloomStrength: 35,
            bloomThreshold: 45,
            grainSize: 1.1,
            fade: 3
        },
        {
            name: "Vericolor III",
            category: "kodak",
            exposure: 0.05,
            contrast: 5,
            highlights: 5,
            shadows: 10,
            whites: 5,
            blacks: 5,
            temperature: 8,
            tint: 5,
            vibrance: 10,
            saturation: 5,
            grain: 10,
            grainGlobal: 1.1,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 1.2,
            fade: 8,
            hslSkin: [5,10,5]
        },
        {
            name: "Tri-X 400",
            category: "kodak",
            exposure: 0.05,
            contrast: 30,
            highlights: 5,
            shadows: -10,
            whites: 15,
            blacks: -15,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 25,
            grainGlobal: 1.4,
            bloomStrength: 10,
            bloomThreshold: 50,
            grainSize: 1.6,
            fade: 5,
            clarity: 10
        },
        {
            name: "T-Max 100",
            category: "kodak",
            description: "Surgical sharpness, tabular grain.",
            exposure: 0,
            contrast: 15,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 5,
            grainSize: 0.5,
            sharpness: 20
        },
        {
            name: "T-Max 400",
            category: "kodak",
            description: "Punchy modern B&W. T-Grain.",
            exposure: 0,
            contrast: 20,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: -5,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 10,
            grainSize: 0.8
        },
        {
            name: "T-Max P3200",
            category: "kodak",
            description: "High speed, beautiful tight grain.",
            exposure: 0,
            contrast: 25,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 35,
            grainSize: 1,
            fade: 5
        },
        {
            name: "Kodak Double-X (5222)",
            category: "kodak",
            description: "Cinematic B&W. Halation & grit.",
            exposure: 0,
            contrast: 30,
            highlights: -10,
            shadows: 10,
            whites: 0,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 20,
            bloomStrength: 30
        },
        {
            name: "Vision3 200T",
            category: "kodak",
            description: "Modern cinema workhorse.",
            exposure: 0,
            contrast: 10,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: -10,
            tint: 0,
            vibrance: 0,
            saturation: 0,
            grain: 8,
            bloomStrength: 25
        },
        {
            name: "Kodak Technical Pan",
            category: "kodak",
            description: "Resolution King. Digital-like detail.",
            exposure: 0,
            contrast: 20,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: -10,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 0,
            sharpness: 40
        },
        {
            name: "Kodak HIE (High Speed Infrared)",
            category: "kodak",
            description: "Ghostly bloom. Exploding highlights.",
            exposure: 0,
            contrast: 30,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 30,
            bloomStrength: 80,
            bloomThreshold: 20
        },
        {
            name: "Kodak Vision 2383 (Print)",
            category: "kodak",
            description: "Hollywood Print. Teal & Orange.",
            exposure: 0,
            contrast: 20,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 10,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: 15,
            splitShadowHue: 180,
            splitHighlightHue: 40
        },
        {
            name: "Kodak Royal Gold 400",
            category: "kodak",
            description: "Premium Consumer. Golden vacation glow.",
            exposure: 0,
            contrast: 10,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: 15,
            tint: 5,
            vibrance: 20,
            saturation: 0,
            hslYellow: [0,20,0]
        },
        {
            name: "Kodak Aerochrome III (1443)",
            category: "kodak",
            description: "Bubblegum Pink IR. Distinct from generic Red.",
            exposure: 0,
            contrast: 0,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: 0,
            tint: 30,
            vibrance: 0,
            saturation: 30,
            bloomStrength: 40,
            hslGreen: [-80,50,20]
        },
        {
            name: "Silbersalz 200T",
            category: "kodak",
            description: "Cinematic tungsten, soft contrast.",
            exposure: 0.05,
            contrast: 5,
            highlights: -15,
            shadows: 10,
            whites: -5,
            blacks: 5,
            temperature: -10,
            tint: 0,
            vibrance: -5,
            saturation: 5,
            grain: 10,
            grainGlobal: 1,
            bloomStrength: 25,
            bloomThreshold: 60,
            hslBlue: [0,10,0]
        },
        {
            name: "Silbersalz 50D",
            category: "kodak",
            description: "Pristine daylight motion picture film.",
            exposure: 0.05,
            contrast: 5,
            highlights: -5,
            shadows: 5,
            whites: 5,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: 10,
            saturation: 10,
            grain: 2,
            grainGlobal: 0.8,
            bloomStrength: 10,
            bloomThreshold: 70
        },
        {
            name: "Kodak Aerochrome",
            category: "kodak",
            description: "Infrared simulation. Vegetation turns red/pink.",
            exposure: 0.05,
            contrast: 30,
            highlights: 10,
            shadows: -10,
            whites: 10,
            blacks: -10,
            temperature: 0,
            tint: 50,
            vibrance: 40,
            saturation: 30,
            grain: 20,
            grainGlobal: 1.4,
            bloomStrength: 40,
            bloomThreshold: 50,
            hslGreen: [-120,50,10],
            hslYellow: [-40,30,0]
        },
        {
            name: "Aerochrome",
            category: "kodak",
            description: "Infrared Simulation. Green becomes Red.",
            exposure: 0.1,
            contrast: 25,
            highlights: 15,
            shadows: -10,
            whites: 10,
            blacks: -10,
            temperature: 10,
            tint: 50,
            vibrance: 30,
            saturation: 20,
            grain: 20,
            grainGlobal: 1.5,
            bloomStrength: 50,
            bloomThreshold: 40,
            grainSize: 1.5,
            fade: 0,
            hslGreen: [-100,50,0],
            splitHighlightHue: 350,
            splitHighlightSat: 40
        },
        {
            name: "Kodak FunSaver",
            category: "kodak",
            description: "The classic party camera. Warm, plastic lens softness.",
            exposure: 0.1,
            contrast: 15,
            highlights: -5,
            shadows: 10,
            whites: 5,
            blacks: 5,
            temperature: 8,
            tint: 2,
            vibrance: 15,
            saturation: 10,
            grain: 12,
            grainGlobal: 1,
            bloomStrength: 10,
            bloomThreshold: 65,
            grainSize: 1.3,
            fade: 2,
            vignette: 0.3,
            hslYellow: [0,10,5],
            hslRed: [0,5,0]
        },
        {
            name: "Kodak Daylight",
            category: "kodak",
            description: "Balanced for outdoors. Slightly flat but natural.",
            exposure: 0.05,
            contrast: 5,
            highlights: -15,
            shadows: 5,
            whites: 0,
            blacks: 0,
            temperature: 5,
            tint: 0,
            vibrance: 10,
            saturation: 5,
            grain: 8,
            grainGlobal: 0.9,
            bloomStrength: 5,
            bloomThreshold: 80,
            grainSize: 1,
            fade: 0
        }
    ],

    // ============ FUJI ============
    fuji: [
        {
            name: "Pro 400H",
            category: "fuji",
            exposure: 0.05,
            contrast: -10,
            highlights: -15,
            shadows: 20,
            whites: -10,
            blacks: 8,
            temperature: -5,
            tint: 8,
            vibrance: -5,
            saturation: -10,
            grain: 6,
            grainGlobal: 1,
            bloomStrength: 20,
            bloomThreshold: 65,
            grainSize: 1.1,
            fade: 8
        },
        {
            name: "Superia 400",
            category: "fuji",
            exposure: 0.08,
            contrast: 5,
            highlights: 5,
            shadows: 10,
            whites: 5,
            blacks: 5,
            temperature: 5,
            tint: 10,
            vibrance: 15,
            saturation: 10,
            grain: 12,
            grainGlobal: 1.1,
            bloomStrength: 10,
            bloomThreshold: 70,
            grainSize: 1.3,
            fade: 5
        },
        {
            name: "Superia 800",
            category: "fuji",
            exposure: 0.1,
            contrast: 3,
            highlights: 8,
            shadows: 15,
            whites: 8,
            blacks: 8,
            temperature: 8,
            tint: 12,
            vibrance: 12,
            saturation: 8,
            grain: 18,
            grainGlobal: 1.3,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 1.6,
            fade: 8
        },
        {
            name: "C200",
            category: "fuji",
            exposure: 0.05,
            contrast: 8,
            highlights: 0,
            shadows: 5,
            whites: 3,
            blacks: 0,
            temperature: 8,
            tint: 5,
            vibrance: 10,
            saturation: 8,
            grain: 10,
            grainGlobal: 1,
            bloomStrength: 10,
            bloomThreshold: 70,
            grainSize: 1.2,
            fade: 3
        },
        {
            name: "Velvia 50",
            category: "fuji",
            exposure: -0.05,
            contrast: 25,
            highlights: -10,
            shadows: -20,
            whites: 15,
            blacks: -15,
            temperature: 0,
            tint: 0,
            vibrance: 35,
            saturation: 30,
            grain: 2,
            grainGlobal: 0.5,
            bloomStrength: 5,
            bloomThreshold: 85,
            grainSize: 0.6,
            fade: 0
        },
        {
            name: "Velvia 100",
            category: "fuji",
            exposure: 0,
            contrast: 20,
            highlights: -8,
            shadows: -15,
            whites: 12,
            blacks: -12,
            temperature: 0,
            tint: 0,
            vibrance: 30,
            saturation: 25,
            grain: 3,
            grainGlobal: 0.6,
            bloomStrength: 5,
            bloomThreshold: 80,
            grainSize: 0.7,
            fade: 0
        },
        {
            name: "Provia 100F",
            category: "fuji",
            exposure: 0,
            contrast: 15,
            highlights: -5,
            shadows: -8,
            whites: 8,
            blacks: -8,
            temperature: -3,
            tint: 0,
            vibrance: 15,
            saturation: 12,
            grain: 2,
            grainGlobal: 0.5,
            bloomStrength: 8,
            bloomThreshold: 75,
            grainSize: 0.6,
            fade: 0
        },
        {
            name: "Astia 100F",
            category: "fuji",
            exposure: 0.03,
            contrast: 8,
            highlights: -8,
            shadows: 5,
            whites: 3,
            blacks: 0,
            temperature: 3,
            tint: 3,
            vibrance: 8,
            saturation: 5,
            grain: 2,
            grainGlobal: 0.5,
            bloomStrength: 12,
            bloomThreshold: 70,
            grainSize: 0.6,
            fade: 0
        },
        {
            name: "Classic Chrome",
            category: "fuji",
            exposure: 0,
            contrast: 12,
            highlights: -15,
            shadows: 5,
            whites: -5,
            blacks: 5,
            temperature: -5,
            tint: 0,
            vibrance: -15,
            saturation: -20,
            grain: 5,
            grainGlobal: 0.8,
            bloomStrength: 5,
            bloomThreshold: 80,
            grainSize: 1,
            fade: 10
        },
        {
            name: "Eterna Cinema",
            category: "fuji",
            exposure: 0,
            contrast: -5,
            highlights: -20,
            shadows: 15,
            whites: -15,
            blacks: 10,
            temperature: -10,
            tint: 5,
            vibrance: -20,
            saturation: -15,
            grain: 3,
            grainGlobal: 0.7,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 0.8,
            fade: 15
        },
        {
            name: "Natura 1600",
            category: "fuji",
            description: "The 'Dream Film'. High key, pastel pinks, soft contrast.",
            exposure: 0.15,
            contrast: -15,
            highlights: -10,
            shadows: 25,
            whites: -5,
            blacks: 15,
            temperature: 5,
            tint: 15,
            vibrance: 10,
            saturation: 5,
            grain: 25,
            grainGlobal: 1.5,
            bloomStrength: 40,
            bloomThreshold: 45,
            grainSize: 1.5,
            fade: 10,
            hslMagenta: [0,20,10],
            hslGreen: [10,-10,5]
        },
        {
            name: "Fortia SP",
            category: "fuji",
            description: "Ultra-high saturation, famous for cherry blossoms.",
            exposure: 0,
            contrast: 20,
            highlights: 5,
            shadows: -5,
            whites: 10,
            blacks: -5,
            temperature: 5,
            tint: 20,
            vibrance: 40,
            saturation: 35,
            grain: 10,
            grainGlobal: 1,
            bloomStrength: 10,
            bloomThreshold: 70,
            grainSize: 1.2,
            fade: 0,
            hslRed: [0,20,0],
            hslMagenta: [5,30,0]
        },
        {
            name: "Neopan 1600",
            category: "fuji",
            exposure: 0.1,
            contrast: 40,
            highlights: 10,
            shadows: -15,
            whites: 20,
            blacks: -20,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 35,
            grainGlobal: 1.6,
            bloomStrength: 20,
            bloomThreshold: 50,
            grainSize: 1.8,
            fade: 5
        },
        {
            name: "Neopan Acros 100",
            category: "fuji",
            description: "Orthopanchromatic. Crushed blacks.",
            exposure: 0,
            contrast: 25,
            highlights: 0,
            shadows: 0,
            whites: 10,
            blacks: -15,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 3
        },
        {
            name: "Fujifilm FP-100C",
            category: "fuji",
            description: "Peel-apart icon. Rich sat, cool blues.",
            exposure: 0,
            contrast: 15,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: -5,
            tint: -5,
            vibrance: 20,
            saturation: 30,
            hslBlue: [0,10,-5]
        },
        {
            name: "Fuji QuickSnap",
            category: "fuji",
            description: "Vivid greens and blues. Sharp center, soft edges.",
            exposure: 0.05,
            contrast: 10,
            highlights: -10,
            shadows: 5,
            whites: 5,
            blacks: 5,
            temperature: -5,
            tint: 5,
            vibrance: 20,
            saturation: 15,
            grain: 10,
            grainGlobal: 0.9,
            bloomStrength: 10,
            bloomThreshold: 70,
            grainSize: 1.2,
            fade: 0,
            vignette: 0.25,
            hslGreen: [5,15,0],
            hslBlue: [0,10,0]
        }
    ],

    // ============ ILFORD ============
    ilford: [
        {
            name: "HP5 Plus 400",
            category: "ilford",
            exposure: 0.05,
            contrast: 15,
            highlights: -5,
            shadows: 10,
            whites: 5,
            blacks: -5,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 15,
            grainGlobal: 1.2,
            bloomStrength: 10,
            bloomThreshold: 60,
            grainSize: 1.4,
            fade: 5
        },
        {
            name: "Delta 100",
            category: "ilford",
            exposure: 0,
            contrast: 20,
            highlights: -10,
            shadows: -5,
            whites: 10,
            blacks: -10,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 5,
            grainGlobal: 0.8,
            bloomStrength: 5,
            bloomThreshold: 80,
            grainSize: 0.8,
            fade: 0
        },
        {
            name: "Delta 400",
            category: "ilford",
            exposure: 0.03,
            contrast: 18,
            highlights: -8,
            shadows: 5,
            whites: 8,
            blacks: -5,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 12,
            grainGlobal: 1,
            bloomStrength: 8,
            bloomThreshold: 70,
            grainSize: 1.2,
            fade: 3
        },
        {
            name: "Delta 3200",
            category: "ilford",
            exposure: 0.1,
            contrast: 12,
            highlights: 0,
            shadows: 15,
            whites: 5,
            blacks: 5,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 25,
            grainGlobal: 1.5,
            bloomStrength: 15,
            bloomThreshold: 50,
            grainSize: 2,
            fade: 8
        },
        {
            name: "FP4 Plus 125",
            category: "ilford",
            exposure: 0,
            contrast: 22,
            highlights: -12,
            shadows: -8,
            whites: 12,
            blacks: -12,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 4,
            grainGlobal: 0.7,
            bloomStrength: 5,
            bloomThreshold: 75,
            grainSize: 0.7,
            fade: 0
        },
        {
            name: "Pan F Plus 50",
            category: "ilford",
            exposure: -0.03,
            contrast: 25,
            highlights: -15,
            shadows: -12,
            whites: 15,
            blacks: -15,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 2,
            grainGlobal: 0.5,
            bloomStrength: 2,
            bloomThreshold: 90,
            grainSize: 0.5,
            fade: 0
        },
        {
            name: "XP2 Super",
            category: "ilford",
            exposure: 0.05,
            contrast: 10,
            highlights: -5,
            shadows: 10,
            whites: 0,
            blacks: 0,
            temperature: 5,
            tint: 3,
            vibrance: 0,
            saturation: -100,
            grain: 8,
            grainGlobal: 1,
            bloomStrength: 12,
            bloomThreshold: 60,
            grainSize: 1,
            fade: 5
        },
        {
            name: "SFX 200",
            category: "ilford",
            exposure: 0.08,
            contrast: 30,
            highlights: 10,
            shadows: -20,
            whites: 20,
            blacks: -20,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 10,
            grainGlobal: 1.3,
            bloomStrength: 40,
            bloomThreshold: 40,
            grainSize: 1.1,
            fade: 0
        },
        {
            name: "HP5 Plus 800",
            category: "ilford",
            exposure: 0.1,
            contrast: 15,
            highlights: -5,
            shadows: 15,
            whites: 5,
            blacks: 5,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 20,
            grainGlobal: 1.4,
            bloomStrength: 20,
            bloomThreshold: 55,
            grainSize: 1.6,
            fade: 8
        },
        {
            name: "Ortho 80",
            category: "ilford",
            exposure: -0.05,
            contrast: 35,
            highlights: 15,
            shadows: -25,
            whites: 20,
            blacks: -25,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 5,
            grainGlobal: 0.8,
            bloomStrength: 5,
            bloomThreshold: 80,
            grainSize: 0.7,
            fade: 0
        },
        {
            name: "Ilford HP5 Single",
            category: "ilford",
            description: "Gritty B&W disposable. High contrast.",
            exposure: 0.05,
            contrast: 25,
            highlights: 5,
            shadows: 10,
            whites: 5,
            blacks: -10,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 25,
            grainGlobal: 1.4,
            bloomStrength: 10,
            bloomThreshold: 55,
            grainSize: 1.6,
            fade: 5,
            vignette: 0.35
        },
        {
            name: "Ilford XP2 Single",
            category: "ilford",
            description: "Smooth C41 B&W. Creamy tones.",
            exposure: 0.05,
            contrast: 10,
            highlights: -5,
            shadows: 15,
            whites: -5,
            blacks: 5,
            temperature: 5,
            tint: 2,
            vibrance: 0,
            saturation: -100,
            grain: 10,
            grainGlobal: 1,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 1.1,
            fade: 8,
            vignette: 0.2
        }
    ],

    // ============ CINESTILL ============
    cinestill: [
        {
            name: "Cinestill 800T",
            category: "cinestill",
            description: "Tungsten balanced with iconic red halation.",
            exposure: 0.05,
            contrast: 10,
            highlights: -15,
            shadows: 10,
            whites: 5,
            blacks: -5,
            temperature: -25,
            tint: 0,
            vibrance: 10,
            saturation: 5,
            grain: 12,
            grainGlobal: 1.2,
            bloomStrength: 35,
            bloomThreshold: 50,
            grainSize: 1.3,
            fade: 5,
            halation: 50
        },
        {
            name: "Cinestill 800T",
            category: "cinestill",
            description: "Tungsten balanced, famous red halation around lights.",
            exposure: 0.1,
            contrast: 10,
            highlights: -20,
            shadows: 15,
            whites: -10,
            blacks: 10,
            temperature: -15,
            tint: 5,
            vibrance: 10,
            saturation: 5,
            grain: 12,
            grainGlobal: 1.1,
            bloomStrength: 50,
            bloomThreshold: 35,
            grainSize: 1.2,
            fade: 5,
            hslRed: [0,10,0],
            hslOrange: [0,20,0],
            hslBlue: [-10,10,-5],
            halation: 0.8
        },
        {
            name: "Cinestill 50D",
            category: "cinestill",
            description: "Fine grain daylight film. Sharp and vibrant.",
            exposure: 0.05,
            contrast: 15,
            highlights: -10,
            shadows: 5,
            whites: 5,
            blacks: -5,
            temperature: 5,
            tint: 0,
            vibrance: 20,
            saturation: 15,
            grain: 5,
            grainGlobal: 0.8,
            bloomStrength: 15,
            bloomThreshold: 70,
            grainSize: 0.8,
            fade: 0
        },
        {
            name: "Cinestill 400D",
            category: "cinestill",
            description: "Versatile, natural skin tones, soft halation.",
            exposure: 0.05,
            contrast: 10,
            highlights: -10,
            shadows: 10,
            whites: 0,
            blacks: 5,
            temperature: 5,
            tint: 2,
            vibrance: 10,
            saturation: 10,
            grain: 8,
            grainGlobal: 0.9,
            bloomStrength: 25,
            bloomThreshold: 60,
            grainSize: 1,
            fade: 3
        }
    ],

    // ============ AGFA ============
    agfa: [
        {
            name: "Agfa Vista 200",
            category: "agfa",
            description: "Punchy reds and blues, cheap drugstore look.",
            exposure: 0.05,
            contrast: 20,
            highlights: 10,
            shadows: 5,
            whites: 5,
            blacks: 5,
            temperature: 5,
            tint: 5,
            vibrance: 30,
            saturation: 20,
            grain: 15,
            grainGlobal: 1,
            bloomStrength: 10,
            bloomThreshold: 70,
            grainSize: 1.3,
            fade: 5,
            hslRed: [5,20,5],
            hslBlue: [0,20,0]
        },
        {
            name: "Agfa Ultra 50",
            category: "agfa",
            exposure: 0.1,
            contrast: 35,
            highlights: 10,
            shadows: 5,
            whites: 15,
            blacks: 10,
            temperature: 0,
            tint: 0,
            vibrance: 60,
            saturation: 40,
            hslRed: [0,50,0],
            hslBlue: [0,50,0],
            grain: 15,
            grainSize: 1.4,
            fade: 0
        },
        {
            name: "Agfa LeBox",
            category: "agfa",
            description: "Flash-ready look. Punchy contrast, red/blue shift.",
            exposure: 0.15,
            contrast: 25,
            highlights: 10,
            shadows: 10,
            whites: 10,
            blacks: -5,
            temperature: 5,
            tint: 0,
            vibrance: 25,
            saturation: 20,
            grain: 15,
            grainGlobal: 1.1,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 1.3,
            fade: 0,
            hslRed: [0,20,5]
        }
    ],

    // ============ POLAROID ============
    polaroid: [
        {
            name: "Polaroid 600",
            category: "polaroid",
            description: "Soft focus, faded blacks, greenish cast.",
            exposure: 0.1,
            contrast: -10,
            highlights: -20,
            shadows: 20,
            whites: -15,
            blacks: 20,
            temperature: 0,
            tint: 10,
            vibrance: -10,
            saturation: -15,
            grain: 10,
            grainGlobal: 1.2,
            bloomStrength: 15,
            bloomThreshold: 55,
            grainSize: 1.5,
            fade: 20
        }
    ],

    // ============ LOMOGRAPHY ============
    lomography: [
        {
            name: "LomoPurple",
            category: "lomography",
            description: "Psychedelic purple shift. Greens become purple.",
            exposure: 0,
            contrast: 15,
            highlights: -10,
            shadows: 10,
            whites: 5,
            blacks: 0,
            temperature: -10,
            tint: 40,
            vibrance: 20,
            saturation: 10,
            grain: 15,
            grainGlobal: 1.2,
            bloomStrength: 20,
            bloomThreshold: 60,
            hslGreen: [100,-50,-20],
            hslBlue: [-40,20,0],
            hslMagenta: [0,40,10]
        },
        {
            name: "LomoChrome Purple",
            category: "lomography",
            description: "Surreal spectrum shift. Green becomes purple.",
            exposure: 0,
            contrast: 15,
            highlights: 5,
            shadows: -5,
            whites: 5,
            blacks: -5,
            temperature: 0,
            tint: 30,
            vibrance: 20,
            saturation: 15,
            grain: 15,
            grainGlobal: 1.3,
            bloomStrength: 20,
            bloomThreshold: 60,
            grainSize: 1.4,
            fade: 0,
            hslGreen: [120,0,0],
            splitHighlightHue: 300,
            splitHighlightSat: 30,
            splitShadowHue: 240,
            splitShadowSat: 20
        },
        {
            name: "Lomo Turquoise",
            category: "lomography",
            description: "Shifts warm colors to blue/emerald.",
            exposure: 0,
            contrast: 20,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: -20,
            tint: -30,
            vibrance: 20,
            saturation: 10,
            grain: 15,
            hslRed: [-150,0,0],
            hslOrange: [-150,0,0],
            hslYellow: [-150,0,0]
        },
        {
            name: "Lomo Redscale XR",
            category: "lomography",
            description: "Spooled backwards. Intense red/orange.",
            exposure: 0.1,
            contrast: 20,
            highlights: 10,
            shadows: 20,
            whites: 0,
            blacks: 10,
            temperature: 40,
            tint: 20,
            vibrance: 30,
            saturation: 20,
            grain: 15,
            hslRed: [0,20,10],
            hslYellow: [-10,30,0]
        },
        {
            name: "LomoChrome Purple",
            category: "lomography",
            description: "Green turns Purple. Infrared sim.",
            exposure: 0,
            contrast: 15,
            highlights: 0,
            shadows: 0,
            whites: 5,
            blacks: 0,
            temperature: 0,
            tint: 40,
            vibrance: 20,
            saturation: 10,
            hslGreen: [140,0,0],
            grain: 10,
            grainGlobal: 1
        },
        {
            name: "LomoSimple",
            category: "lomography",
            description: "Toy camera. Heavy vignette, random color shifts.",
            exposure: 0,
            contrast: 20,
            highlights: -5,
            shadows: 5,
            whites: 5,
            blacks: 0,
            temperature: 10,
            tint: 15,
            vibrance: 35,
            saturation: 25,
            grain: 15,
            grainGlobal: 1.1,
            bloomStrength: 15,
            bloomThreshold: 50,
            grainSize: 1.2,
            fade: 5,
            vignette: 0.6
        }
    ],

    // ============ KONICA ============
    konica: [
        {
            name: "Konica Centuria 400",
            category: "konica",
            exposure: 0.05,
            contrast: 5,
            highlights: 0,
            shadows: 10,
            whites: 0,
            blacks: 5,
            temperature: -5,
            tint: 15,
            vibrance: 10,
            saturation: 5,
            grain: 18,
            grainGlobal: 1.3,
            bloomStrength: 10,
            bloomThreshold: 65,
            grainSize: 1.4,
            fade: 10
        },
        {
            name: "Konica Centuria",
            category: "konica",
            exposure: 0.05,
            contrast: 10,
            highlights: -15,
            shadows: 10,
            whites: -5,
            blacks: 5,
            temperature: -5,
            tint: 25,
            vibrance: 10,
            saturation: 5,
            grain: 8,
            fade: 10
        }
    ],

    // ============ VINTAGE ============
    vintage: [
        {
            name: "Ferrania Solaris",
            category: "vintage",
            exposure: 0.15,
            contrast: 20,
            highlights: 20,
            shadows: 5,
            whites: 10,
            blacks: 0,
            temperature: 30,
            tint: 5,
            vibrance: 25,
            saturation: 15,
            bloomStrength: 15,
            fade: 5
        },
        {
            name: "Drugstore 400",
            category: "vintage",
            description: "Cheap mall scan. Green shadows, magenta highlights.",
            exposure: 0,
            contrast: 10,
            highlights: -10,
            shadows: 15,
            whites: -5,
            blacks: 10,
            temperature: 0,
            tint: 10,
            vibrance: 5,
            saturation: 5,
            grain: 18,
            grainGlobal: 1.2,
            bloomStrength: 10,
            bloomThreshold: 65,
            grainSize: 1.4,
            fade: 10,
            hslGreen: [0,0,0],
            splitShadowHue: 0.33,
            splitShadowSat: 0.2
        },
        {
            name: "Expired Disposable",
            category: "vintage",
            description: "Found in a drawer after 10 years. Fogged.",
            exposure: 0.1,
            contrast: -25,
            highlights: -30,
            shadows: 30,
            whites: -20,
            blacks: 25,
            temperature: 15,
            tint: 20,
            vibrance: -10,
            saturation: -20,
            grain: 30,
            grainGlobal: 1.5,
            bloomStrength: 40,
            bloomThreshold: 20,
            grainSize: 1.8,
            fade: 25,
            hslBlue: [-20,-30,10]
        },
        {
            name: "Retro PC",
            category: "vintage",
            description: "CGA Graphics era. 4-bit dither.",
            exposure: 0,
            contrast: 50,
            saturation: -20,
            ditherStrength: 100,
            pixelateSize: 4,
            scanlineIntensity: 0,
            grain: 0
        },
        {
            name: "Technicolor 2-Strip",
            category: "vintage",
            exposure: 0.1,
            contrast: 30,
            highlights: 10,
            shadows: -10,
            whites: 10,
            blacks: -5,
            temperature: 0,
            tint: 0,
            vibrance: 20,
            saturation: 10,
            hslBlue: [0,-100,-50],
            hslGreen: [-10,20,0],
            hslRed: [10,30,0],
            fade: 0
        },
        {
            name: "Silent Sepia",
            category: "vintage",
            exposure: 0.1,
            contrast: 20,
            highlights: -10,
            shadows: 10,
            whites: 20,
            blacks: 5,
            temperature: 30,
            tint: 10,
            vibrance: -80,
            saturation: -100,
            grain: 40,
            grainSize: 1.5,
            filmGateWeave: 50,
            fade: 15
        }
    ],

    // ============ OBSCURE ============
    obscure: [
        {
            name: "Orwo Wolfen NC500",
            category: "obscure",
            description: "German cinema look. Desaturated & gritty.",
            exposure: 0,
            contrast: 10,
            highlights: -10,
            shadows: 10,
            whites: -5,
            blacks: 5,
            temperature: -5,
            tint: 15,
            vibrance: -20,
            saturation: -25,
            grain: 12,
            grainGlobal: 1.1,
            fade: 5
        },
        {
            name: "Revolog Kolor",
            category: "obscure",
            description: "Artificial rainbow gradients.",
            exposure: 0.1,
            contrast: 10,
            highlights: -10,
            shadows: 10,
            whites: 0,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: 30,
            saturation: 20,
            lightLeak: 80,
            grain: 20
        },
        {
            name: "Perutz Primera",
            category: "obscure",
            exposure: -0.05,
            contrast: 25,
            highlights: -20,
            shadows: -10,
            whites: -15,
            blacks: -5,
            temperature: 10,
            tint: -5,
            vibrance: -30,
            saturation: -40,
            hslGreen: [-10,-30,-10],
            hslOrange: [-5,-20,0],
            grain: 25,
            grainSize: 1.5,
            fade: 15
        }
    ],

    // ============ MODERN ============
    modern: [
        {
            name: "Ektachrome E100",
            category: "modern",
            exposure: 0.1,
            contrast: 12,
            highlights: -8,
            shadows: -5,
            whites: 10,
            blacks: -8,
            temperature: -4,
            tint: 0,
            vibrance: 25,
            saturation: 15,
            grain: 5,
            grainGlobal: 0.9,
            bloomStrength: 10,
            bloomThreshold: 70,
            grainSize: 0.9,
            fade: 0
        },
        {
            name: "Kodachrome 25",
            category: "modern",
            exposure: 0,
            contrast: 20,
            highlights: 10,
            shadows: -15,
            whites: 5,
            blacks: -10,
            temperature: 5,
            tint: 5,
            vibrance: 40,
            saturation: 25,
            grain: 12,
            grainGlobal: 1,
            bloomStrength: 5,
            bloomThreshold: 80,
            grainSize: 1.1,
            fade: 0
        },
        {
            name: "Ektachrome 64T",
            category: "modern",
            exposure: 0,
            contrast: 10,
            highlights: -10,
            shadows: 5,
            whites: 0,
            blacks: -5,
            temperature: -15,
            tint: 10,
            vibrance: 15,
            saturation: 10,
            grain: 15,
            grainGlobal: 1.1,
            bloomStrength: 20,
            bloomThreshold: 55,
            grainSize: 1.2,
            fade: 5
        },
        {
            name: "Ektachrome E100 Warm",
            category: "modern",
            exposure: 0,
            contrast: 20,
            highlights: -10,
            shadows: -15,
            whites: 10,
            blacks: -10,
            temperature: -8,
            tint: -5,
            vibrance: 25,
            saturation: 20,
            grain: 3,
            grainGlobal: 0.8,
            bloomStrength: 12,
            bloomThreshold: 65,
            grainSize: 0.7,
            fade: 0
        },
        {
            name: "Kodachrome 64",
            category: "modern",
            exposure: 0,
            contrast: 25,
            highlights: 10,
            shadows: -15,
            whites: 5,
            blacks: -10,
            temperature: 5,
            tint: 5,
            vibrance: 20,
            saturation: 15,
            grain: 5,
            grainGlobal: 1,
            bloomStrength: 5,
            bloomThreshold: 75,
            grainSize: 0.8,
            fade: 0,
            hslRed: [0,10,-5],
            hslYellow: [0,15,0],
            hslBlue: [0,20,-10]
        },
        {
            name: "Ektachrome E100VS",
            category: "modern",
            exposure: 0.05,
            contrast: 20,
            highlights: 5,
            shadows: -5,
            whites: 10,
            blacks: -5,
            temperature: -5,
            tint: 0,
            vibrance: 30,
            saturation: 25,
            grain: 8,
            grainGlobal: 1,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 1,
            fade: 0,
            hslBlue: [0,30,0]
        },
        {
            name: "Infrared B&W",
            category: "modern",
            exposure: 0.1,
            contrast: 40,
            highlights: 15,
            shadows: -20,
            whites: 20,
            blacks: -20,
            temperature: 0,
            tint: 0,
            vibrance: -100,
            saturation: -100,
            grain: 15,
            grainGlobal: 1.2,
            bloomStrength: 30,
            bloomThreshold: 45,
            grainSize: 1.2,
            fade: 0,
            hslGreen: [0,50,50],
            hslBlue: [0,-50,-50]
        },
        {
            name: "Bleach Bypass",
            category: "modern",
            exposure: -0.1,
            contrast: 40,
            highlights: 15,
            shadows: -15,
            whites: 20,
            blacks: -15,
            temperature: -5,
            tint: 0,
            vibrance: -30,
            saturation: -40,
            grain: 15,
            grainGlobal: 1.4,
            bloomStrength: 10,
            bloomThreshold: 70,
            grainSize: 1.3,
            fade: 0,
            clarity: 20
        },
        {
            name: "Moonlight",
            category: "modern",
            exposure: 0,
            contrast: 5,
            highlights: -25,
            shadows: 20,
            whites: -15,
            blacks: 15,
            temperature: -25,
            tint: 20,
            vibrance: -10,
            saturation: -20,
            grain: 3,
            grainGlobal: 0.8,
            bloomStrength: 25,
            bloomThreshold: 40,
            grainSize: 0.8,
            fade: 20
        },
        {
            name: "Euphoria",
            category: "modern",
            exposure: 0.05,
            contrast: 15,
            highlights: -10,
            shadows: 15,
            whites: 0,
            blacks: 5,
            temperature: -10,
            tint: 25,
            vibrance: 30,
            saturation: 20,
            grain: 3,
            grainGlobal: 1,
            bloomStrength: 50,
            bloomThreshold: 35,
            grainSize: 0.7,
            fade: 10,
            hslMagenta: [0,30,5],
            hslBlue: [10,25,0]
        },
        {
            name: "Sci-Fi Blue",
            category: "modern",
            exposure: 0,
            contrast: 20,
            highlights: -10,
            shadows: 10,
            whites: 5,
            blacks: -5,
            temperature: -30,
            tint: -10,
            vibrance: -20,
            saturation: -30,
            grain: 5,
            grainGlobal: 0.8,
            bloomStrength: 15,
            bloomThreshold: 60,
            fade: 5,
            hslBlue: [0,20,10]
        },
        {
            name: "Western",
            category: "modern",
            exposure: 0.1,
            contrast: 15,
            highlights: 5,
            shadows: 5,
            whites: 0,
            blacks: 5,
            temperature: 25,
            tint: 10,
            vibrance: 10,
            saturation: 0,
            grain: 15,
            grainGlobal: 1.2,
            bloomStrength: 10,
            bloomThreshold: 70,
            fade: 10,
            vignette: 25
        },
        {
            name: "Thriller",
            category: "modern",
            exposure: -0.15,
            contrast: 30,
            highlights: -20,
            shadows: -10,
            whites: -10,
            blacks: -10,
            temperature: -10,
            tint: 30,
            vibrance: -30,
            saturation: -40,
            grain: 12,
            grainGlobal: 1.3,
            bloomStrength: 5,
            fade: 0,
            hslGreen: [0,-20,-10]
        },
        {
            name: "French New Wave",
            category: "modern",
            exposure: 0.15,
            contrast: -10,
            highlights: 10,
            shadows: 15,
            whites: 5,
            blacks: 10,
            temperature: 5,
            tint: 0,
            vibrance: 15,
            saturation: 10,
            grain: 10,
            grainGlobal: 1.1,
            bloomStrength: 20,
            bloomThreshold: 65,
            fade: 10
        },
        {
            name: "Clean & Crisp",
            category: "modern",
            exposure: 0.05,
            contrast: 10,
            highlights: -20,
            shadows: 20,
            whites: -10,
            blacks: 10,
            temperature: 0,
            tint: 0,
            vibrance: 5,
            saturation: 0,
            grain: 0,
            grainGlobal: 0,
            bloomStrength: 0,
            bloomThreshold: 100,
            grainSize: 1,
            fade: 0
        },
        {
            name: "Moody",
            category: "modern",
            exposure: -0.1,
            contrast: 20,
            highlights: -25,
            shadows: 5,
            whites: -15,
            blacks: 0,
            temperature: -15,
            tint: 5,
            vibrance: -10,
            saturation: -15,
            grain: 5,
            grainGlobal: 0.8,
            bloomStrength: 10,
            bloomThreshold: 60,
            grainSize: 1,
            fade: 10,
            vignette: 20
        },
        {
            name: "Light & Airy",
            category: "modern",
            exposure: 0.3,
            contrast: -15,
            highlights: 20,
            shadows: 30,
            whites: 25,
            blacks: 20,
            temperature: 5,
            tint: 5,
            vibrance: -5,
            saturation: -10,
            grain: 0,
            grainGlobal: 0,
            bloomStrength: 20,
            bloomThreshold: 70,
            grainSize: 1,
            fade: 15
        },
        {
            name: "Rich & Bold",
            category: "modern",
            exposure: 0,
            contrast: 25,
            highlights: -15,
            shadows: -10,
            whites: 10,
            blacks: -15,
            temperature: 5,
            tint: 0,
            vibrance: 25,
            saturation: 15,
            grain: 3,
            grainGlobal: 0.8,
            bloomStrength: 5,
            bloomThreshold: 80,
            grainSize: 0.8,
            fade: 0
        },
        {
            name: "Matte Film",
            category: "modern",
            exposure: 0.05,
            contrast: -5,
            highlights: -15,
            shadows: 15,
            whites: -10,
            blacks: 12,
            temperature: 5,
            tint: 3,
            vibrance: -5,
            saturation: -8,
            grain: 8,
            grainGlobal: 1,
            bloomStrength: 10,
            bloomThreshold: 65,
            grainSize: 1.1,
            fade: 20
        },
        {
            name: "Golden Hour",
            category: "modern",
            exposure: 0.15,
            contrast: 5,
            highlights: 10,
            shadows: 20,
            whites: 10,
            blacks: 10,
            temperature: 30,
            tint: 10,
            vibrance: 15,
            saturation: 10,
            grain: 3,
            grainGlobal: 1,
            bloomStrength: 20,
            bloomThreshold: 50,
            grainSize: 0.8,
            fade: 5
        },
        {
            name: "Blue Hour",
            category: "modern",
            exposure: -0.05,
            contrast: 10,
            highlights: -20,
            shadows: 15,
            whites: -10,
            blacks: 10,
            temperature: -30,
            tint: 10,
            vibrance: 10,
            saturation: 5,
            grain: 3,
            grainGlobal: 1,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 0.8,
            fade: 10
        },
        {
            name: "Pastel Dream",
            category: "modern",
            exposure: 0.2,
            contrast: -20,
            highlights: 15,
            shadows: 25,
            whites: 20,
            blacks: 20,
            temperature: 5,
            tint: 15,
            vibrance: 20,
            saturation: -30,
            grain: 0,
            grainGlobal: 0.5,
            bloomStrength: 25,
            bloomThreshold: 60,
            grainSize: 1,
            fade: 25
        },
        {
            name: "Scotch Chrome",
            category: "modern",
            exposure: 0,
            contrast: 15,
            highlights: 0,
            shadows: 15,
            whites: 5,
            blacks: 5,
            temperature: 0,
            tint: 15,
            vibrance: 10,
            saturation: 5,
            hslBlue: [10,0,0],
            hslShadows: [280,20,0],
            grain: 30,
            grainSize: 1.8,
            fade: 10
        },
        {
            name: "Redrum",
            category: "modern",
            description: "Limited edition red-scale film. Intense monochromatic red.",
            exposure: -0.1,
            contrast: 40,
            highlights: 20,
            shadows: -20,
            whites: 10,
            blacks: -10,
            temperature: 20,
            tint: 80,
            vibrance: -50,
            saturation: -80,
            grain: 20,
            grainGlobal: 1.3,
            bloomStrength: 30,
            bloomThreshold: 50,
            hslRed: [0,50,0],
            hslOrange: [-10,30,-10],
            hslYellow: [-20,0,-20]
        },
        {
            name: "Wedding Cam",
            category: "modern",
            description: "Table camera aesthetic. Harsh flash simulation.",
            exposure: 0.2,
            contrast: 30,
            highlights: 20,
            shadows: -10,
            whites: 15,
            blacks: -15,
            temperature: -5,
            tint: 0,
            vibrance: 15,
            saturation: 10,
            grain: 10,
            grainGlobal: 1,
            bloomStrength: 20,
            bloomThreshold: 40,
            grainSize: 1.1,
            fade: 0,
            vignette: 0.5
        },
        {
            name: "Hackerman",
            category: "modern",
            description: "System brea__kdown. Glitch + Dither.",
            exposure: 0.1,
            contrast: 20,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: -20,
            tint: 50,
            hslGreen: [0,50,0],
            hslRed: [0,-100,-50],
            glitchStrength: 30,
            pixelateSize: 0,
            ditherStrength: 20,
            scanlineIntensity: 10,
            grain: 0,
            chromaticAberration: 5
        },
        {
            name: "Cyberpunk",
            category: "modern",
            description: "High tech, low life. Neon aesthetic.",
            exposure: 0.05,
            contrast: 15,
            highlights: 20,
            shadows: 10,
            whites: 10,
            blacks: 10,
            vibrance: 40,
            saturation: 20,
            temperature: -10,
            tint: 20,
            bloomStrength: 50,
            bloomThreshold: 40,
            glitchStrength: 5,
            scanlineIntensity: 20,
            chromaticAberration: 10
        },
        {
            name: "VHS",
            category: "modern",
            description: "Tracking error. Worn tape.",
            exposure: 0.05,
            contrast: 10,
            highlights: -10,
            shadows: 10,
            fade: 30,
            grain: 40,
            grainSize: 2,
            chromaticAberration: 20,
            scanlineIntensity: 50,
            glitchStrength: 2,
            vignette: 0.2,
            distortion: 0
        },
        {
            name: "Vogue",
            category: "modern",
            description: "High fashion contrast. Punchy and sharp.",
            exposure: 0.1,
            contrast: 15,
            highlights: -10,
            shadows: 5,
            whites: 10,
            blacks: -5,
            temperature: 0,
            tint: 0,
            vibrance: 10,
            saturation: -5,
            grain: 0,
            sharpness: 20,
            clarity: 15,
            fade: 0
        },
        {
            name: "Studio Clean",
            category: "modern",
            description: "Perfect skin tones. Soft and neutral.",
            exposure: 0.05,
            contrast: 5,
            highlights: -15,
            shadows: 10,
            whites: -5,
            blacks: 5,
            temperature: 0,
            tint: 0,
            vibrance: 5,
            saturation: 0,
            grain: 0,
            clarity: -5,
            bloomStrength: 5,
            bloomThreshold: 80
        },
        {
            name: "Runway",
            category: "modern",
            description: "Cool and edgy. Modern magazine look.",
            exposure: 0.1,
            contrast: 20,
            highlights: 5,
            shadows: 5,
            whites: 15,
            blacks: -10,
            temperature: -5,
            tint: -5,
            vibrance: 15,
            saturation: 5,
            grain: 5,
            grainSize: 0.8,
            clarity: 10
        },
        {
            name: "High Key",
            category: "modern",
            exposure: 0.3,
            contrast: -20,
            highlights: 25,
            shadows: 30,
            whites: 30,
            blacks: 20,
            temperature: 0,
            tint: 0,
            vibrance: -10,
            saturation: -20,
            grain: 0,
            bloomStrength: 15,
            bloomThreshold: 70,
            fade: 10
        },
        {
            name: "Matte Fashion",
            category: "modern",
            exposure: 0.05,
            contrast: -10,
            highlights: -10,
            shadows: 10,
            whites: -15,
            blacks: 15,
            temperature: 5,
            tint: 0,
            vibrance: -20,
            saturation: -15,
            grain: 5,
            grainGlobal: 0.8,
            fade: 25,
            clarity: 5
        },
        {
            name: "Urban Grit",
            category: "modern",
            exposure: -0.1,
            contrast: 35,
            highlights: -15,
            shadows: -15,
            whites: 10,
            blacks: -10,
            temperature: -5,
            tint: -5,
            vibrance: -40,
            saturation: -50,
            grain: 10,
            grainGlobal: 1,
            clarity: 30,
            fade: 0
        },
        {
            name: "Porcelain",
            category: "modern",
            exposure: 0.15,
            contrast: 5,
            highlights: -10,
            shadows: 15,
            whites: 5,
            blacks: 10,
            temperature: -5,
            tint: 10,
            vibrance: 10,
            saturation: 0,
            grain: 0,
            clarity: -15,
            bloomStrength: 10,
            fade: 5
        },
        {
            name: "Deep Forest",
            category: "modern",
            exposure: -0.1,
            contrast: 20,
            highlights: -15,
            shadows: -10,
            whites: -5,
            blacks: -5,
            temperature: 0,
            tint: 10,
            vibrance: 20,
            saturation: 10,
            grain: 5,
            fade: 5,
            hslGreen: [0,20,-10]
        },
        {
            name: "Desert Heat",
            category: "modern",
            exposure: 0.1,
            contrast: 15,
            highlights: 10,
            shadows: 5,
            whites: 5,
            blacks: 0,
            temperature: 25,
            tint: 5,
            vibrance: 15,
            saturation: -10,
            grain: 8,
            clarity: 15,
            fade: 5,
            hslOrange: [0,20,0]
        },
        {
            name: "Ocean Air",
            category: "modern",
            exposure: 0.15,
            contrast: 5,
            highlights: 15,
            shadows: 10,
            whites: 10,
            blacks: 5,
            temperature: -10,
            tint: 0,
            vibrance: 25,
            saturation: 10,
            grain: 3,
            fade: 0,
            hslBlue: [-5,20,5],
            hslAqua: [0,25,10]
        },
        {
            name: "Alpine",
            category: "modern",
            exposure: 0.1,
            contrast: 25,
            highlights: 10,
            shadows: 5,
            whites: 20,
            blacks: 10,
            temperature: -15,
            tint: 0,
            vibrance: 5,
            saturation: 0,
            grain: 2,
            clarity: 20,
            fade: 0,
            hslBlue: [0,10,5]
        },
        {
            name: "Autumn Gold",
            category: "modern",
            exposure: 0.05,
            contrast: 10,
            highlights: -5,
            shadows: 10,
            whites: 5,
            blacks: 5,
            temperature: 15,
            tint: 5,
            vibrance: 30,
            saturation: 20,
            grain: 5,
            fade: 5,
            hslYellow: [-10,25,0],
            hslGreen: [-20,0,0]
        },
        {
            name: "Pastel Goth",
            category: "modern",
            exposure: 0.1,
            contrast: -10,
            highlights: 10,
            shadows: 20,
            whites: 0,
            blacks: 15,
            temperature: -10,
            tint: 20,
            vibrance: -10,
            saturation: -20,
            splitToneBalance: -20,
            hslGreen: [40,-10,20],
            hslRed: [-20,10,10],
            fade: 20
        },
        {
            name: "Electric Indigo",
            category: "modern",
            exposure: -0.2,
            contrast: 40,
            highlights: 30,
            shadows: -30,
            whites: 20,
            blacks: -20,
            temperature: -60,
            tint: 40,
            vibrance: 50,
            saturation: 30,
            bloomStrength: 50,
            bloomThreshold: 20,
            fade: 0
        },
        {
            name: "Solarized",
            category: "modern",
            exposure: 0,
            contrast: 100,
            highlights: -100,
            shadows: -100,
            whites: 100,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: -20,
            saturation: -50,
            posterize: 10,
            fade: 0
        },
        {
            name: "Crimson Tide",
            category: "modern",
            exposure: -0.1,
            contrast: 50,
            highlights: 10,
            shadows: -20,
            whites: 10,
            blacks: -10,
            temperature: 40,
            tint: 60,
            vibrance: -50,
            saturation: -60,
            hslRed: [0,50,20],
            fade: 0
        },
        {
            name: "Golden Age",
            category: "modern",
            exposure: -0.2,
            contrast: 40,
            highlights: 30,
            shadows: -50,
            whites: 10,
            blacks: -30,
            temperature: 25,
            tint: 5,
            vibrance: 20,
            saturation: 10,
            grain: 5,
            vignette: 60,
            fade: 5
        },
        {
            name: "Bleach Bypass",
            category: "modern",
            exposure: 0,
            contrast: 60,
            highlights: 20,
            shadows: -20,
            whites: 15,
            blacks: -25,
            temperature: -5,
            tint: 0,
            vibrance: -40,
            saturation: -60,
            grain: 20,
            grainSize: 1.2,
            fade: 0
        },
        {
            name: "Day for Night",
            category: "modern",
            exposure: -1.5,
            contrast: 10,
            highlights: -50,
            shadows: 10,
            whites: -40,
            blacks: 0,
            temperature: -50,
            tint: 10,
            vibrance: -20,
            saturation: -30,
            fade: 20,
            vignette: 40
        },
        {
            name: "Grindhouse",
            category: "modern",
            exposure: 0,
            contrast: 50,
            highlights: -20,
            shadows: 20,
            whites: -30,
            blacks: 20,
            temperature: 20,
            tint: 15,
            vibrance: 0,
            saturation: -20,
            grain: 60,
            grainSize: 2,
            filmGateWeave: 80,
            vignette: 70,
            fade: 30
        }
    ],

    // ============ MOODY ============
    moody: [
        {
            name: "Dark & Stormy",
            category: "moody",
            exposure: -0.15,
            contrast: 25,
            highlights: -30,
            shadows: -15,
            whites: -20,
            blacks: -10,
            temperature: -15,
            tint: 5,
            vibrance: -10,
            saturation: -20,
            grain: 10,
            grainGlobal: 1.2,
            bloomStrength: 10,
            bloomThreshold: 60,
            grainSize: 1.3,
            fade: 8,
            vignette: 30
        },
        {
            name: "Melancholy",
            category: "moody",
            exposure: -0.05,
            contrast: 10,
            highlights: -25,
            shadows: 10,
            whites: -15,
            blacks: 5,
            temperature: -10,
            tint: 10,
            vibrance: -25,
            saturation: -30,
            grain: 8,
            grainGlobal: 1.1,
            bloomStrength: 15,
            bloomThreshold: 55,
            grainSize: 1.2,
            fade: 20
        },
        {
            name: "Midnight Blues",
            category: "moody",
            exposure: -0.1,
            contrast: 15,
            highlights: -20,
            shadows: 5,
            whites: -10,
            blacks: 0,
            temperature: -40,
            tint: 15,
            vibrance: 5,
            saturation: -10,
            grain: 5,
            grainGlobal: 1,
            bloomStrength: 20,
            bloomThreshold: 50,
            grainSize: 1,
            fade: 15
        },
        {
            name: "Gothic",
            category: "moody",
            exposure: -0.2,
            contrast: 35,
            highlights: -35,
            shadows: -20,
            whites: -25,
            blacks: -15,
            temperature: -20,
            tint: 0,
            vibrance: -30,
            saturation: -40,
            grain: 12,
            grainGlobal: 1.4,
            bloomStrength: 5,
            bloomThreshold: 80,
            grainSize: 1.4,
            fade: 5,
            vignette: 40
        },
        {
            name: "Rainy Day",
            category: "moody",
            exposure: 0,
            contrast: 5,
            highlights: -20,
            shadows: 15,
            whites: -10,
            blacks: 10,
            temperature: -25,
            tint: 5,
            vibrance: -15,
            saturation: -25,
            grain: 6,
            grainGlobal: 0.9,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 1.1,
            fade: 18
        },
        {
            name: "Brooding",
            category: "moody",
            exposure: -0.1,
            contrast: 20,
            highlights: -30,
            shadows: 0,
            whites: -15,
            blacks: -5,
            temperature: -5,
            tint: 8,
            vibrance: -20,
            saturation: -25,
            grain: 10,
            grainGlobal: 1.2,
            bloomStrength: 10,
            bloomThreshold: 65,
            grainSize: 1.3,
            fade: 12,
            vignette: 25
        },
        {
            name: "Twilight",
            category: "moody",
            exposure: -0.05,
            contrast: 12,
            highlights: -25,
            shadows: 10,
            whites: -15,
            blacks: 5,
            temperature: -30,
            tint: 20,
            vibrance: 0,
            saturation: -15,
            grain: 4,
            grainGlobal: 1,
            bloomStrength: 25,
            bloomThreshold: 45,
            grainSize: 0.9,
            fade: 15
        },
        {
            name: "Foggy Morning",
            category: "moody",
            exposure: 0.1,
            contrast: -15,
            highlights: 10,
            shadows: 20,
            whites: 5,
            blacks: 15,
            temperature: -10,
            tint: 0,
            vibrance: -15,
            saturation: -25,
            grain: 20,
            grainGlobal: 1.5,
            bloomStrength: 40,
            bloomThreshold: 40,
            grainSize: 1,
            fade: 25,
            dehaze: -20
        },
        {
            name: "Deep Forest",
            category: "moody",
            exposure: -0.15,
            contrast: 20,
            highlights: -20,
            shadows: -15,
            whites: -10,
            blacks: -10,
            temperature: 5,
            tint: 15,
            vibrance: -10,
            saturation: -30,
            grain: 5,
            grainGlobal: 1,
            bloomStrength: 10,
            bloomThreshold: 60,
            grainSize: 1.2,
            fade: 5,
            hslGreen: [-10,-20,-20]
        },
        {
            name: "Stormy Seas",
            category: "moody",
            exposure: -0.1,
            contrast: 25,
            highlights: 5,
            shadows: -20,
            whites: 10,
            blacks: -15,
            temperature: -15,
            tint: 0,
            vibrance: -25,
            saturation: -40,
            grain: 12,
            grainGlobal: 1.3,
            bloomStrength: 15,
            bloomThreshold: 55,
            grainSize: 1.5,
            fade: 0,
            hslBlue: [-10,-10,-10]
        },
        {
            name: "Silent Night",
            category: "moody",
            exposure: -0.15,
            contrast: 18,
            highlights: -30,
            shadows: 5,
            whites: -20,
            blacks: 0,
            temperature: -35,
            tint: 10,
            vibrance: -15,
            saturation: -20,
            grain: 8,
            grainGlobal: 1.1,
            bloomStrength: 20,
            bloomThreshold: 50,
            grainSize: 1.2,
            fade: 10,
            vignette: 20
        },
        {
            name: "Overcast",
            category: "moody",
            exposure: 0.05,
            contrast: 0,
            highlights: -15,
            shadows: 15,
            whites: -5,
            blacks: 10,
            temperature: -15,
            tint: 5,
            vibrance: -25,
            saturation: -35,
            grain: 3,
            grainGlobal: 0.8,
            bloomStrength: 10,
            bloomThreshold: 70,
            grainSize: 0.8,
            fade: 20
        }
    ],

    // ============ DREAMY ============
    dreamy: [
        {
            name: "Cotton Candy",
            category: "dreamy",
            exposure: 0.25,
            contrast: -25,
            highlights: 20,
            shadows: 30,
            whites: 25,
            blacks: 25,
            temperature: 10,
            tint: 25,
            vibrance: 30,
            saturation: -20,
            grain: 0,
            grainSize: 1,
            fade: 30
        },
        {
            name: "Soft Focus",
            category: "dreamy",
            exposure: 0.15,
            contrast: -20,
            highlights: 15,
            shadows: 25,
            whites: 20,
            blacks: 20,
            temperature: 15,
            tint: 10,
            vibrance: -10,
            saturation: -15,
            grain: 0,
            grainSize: 1,
            fade: 25
        },
        {
            name: "Morning Haze",
            category: "dreamy",
            exposure: 0.2,
            contrast: -15,
            highlights: 25,
            shadows: 20,
            whites: 30,
            blacks: 15,
            temperature: 20,
            tint: 5,
            vibrance: -5,
            saturation: -20,
            grain: 2,
            grainSize: 0.7,
            fade: 35
        },
        {
            name: "Ethereal",
            category: "dreamy",
            exposure: 0.3,
            contrast: -30,
            highlights: 30,
            shadows: 35,
            whites: 35,
            blacks: 30,
            temperature: 5,
            tint: 15,
            vibrance: 15,
            saturation: -25,
            grain: 0,
            grainSize: 1,
            fade: 40
        },
        {
            name: "Fairy Tale",
            category: "dreamy",
            exposure: 0.2,
            contrast: -10,
            highlights: 20,
            shadows: 25,
            whites: 25,
            blacks: 20,
            temperature: 25,
            tint: 20,
            vibrance: 25,
            saturation: 0,
            grain: 3,
            grainSize: 0.8,
            fade: 20
        },
        {
            name: "Lavender Fields",
            category: "dreamy",
            exposure: 0.15,
            contrast: -15,
            highlights: 15,
            shadows: 20,
            whites: 20,
            blacks: 15,
            temperature: -10,
            tint: 30,
            vibrance: 20,
            saturation: -10,
            grain: 2,
            grainSize: 0.8,
            fade: 25
        },
        {
            name: "Cloud Nine",
            category: "dreamy",
            exposure: 0.35,
            contrast: -35,
            highlights: 35,
            shadows: 40,
            whites: 40,
            blacks: 35,
            temperature: 0,
            tint: 10,
            vibrance: 10,
            saturation: -30,
            grain: 0,
            grainSize: 1,
            fade: 45
        },
        {
            name: "Rose Tinted",
            category: "dreamy",
            exposure: 0.2,
            contrast: -20,
            highlights: 20,
            shadows: 25,
            whites: 25,
            blacks: 20,
            temperature: 15,
            tint: 35,
            vibrance: 15,
            saturation: -15,
            grain: 0,
            grainSize: 1,
            fade: 28
        },
        {
            name: "Sunbeam",
            category: "dreamy",
            exposure: 0.25,
            contrast: -10,
            highlights: 30,
            shadows: 20,
            whites: 35,
            blacks: 15,
            temperature: 35,
            tint: 15,
            vibrance: 10,
            saturation: -5,
            grain: 3,
            grainSize: 0.9,
            fade: 22
        },
        {
            name: "Watercolor",
            category: "dreamy",
            exposure: 0.2,
            contrast: -25,
            highlights: 25,
            shadows: 30,
            whites: 30,
            blacks: 25,
            temperature: 5,
            tint: 20,
            vibrance: 35,
            saturation: -35,
            grain: 0,
            grainSize: 1,
            fade: 32
        }
    ],

    // ============ MONOCHROME ============
    monochrome: [
        {
            name: "Noir Soft",
            category: "monochrome",
            exposure: -0.05,
            contrast: 15,
            highlights: -10,
            shadows: 5,
            whites: -5,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 10,
            grainGlobal: 1,
            bloomStrength: 40,
            bloomThreshold: 40,
            grainSize: 1,
            fade: 10
        },
        {
            name: "Newsprint",
            category: "monochrome",
            exposure: 0.1,
            contrast: 50,
            highlights: 10,
            shadows: -10,
            whites: 10,
            blacks: -10,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 40,
            grainGlobal: 2,
            bloomStrength: 0,
            grainSize: 1.5,
            fade: 0,
            clarity: 20
        },
        {
            name: "Noir City",
            category: "monochrome",
            exposure: -0.15,
            contrast: 30,
            highlights: 0,
            shadows: -20,
            whites: 10,
            blacks: -10,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 18,
            grainGlobal: 1.3,
            bloomStrength: 30,
            bloomThreshold: 50,
            grainSize: 1.4,
            fade: 2,
            vignette: 0.4
        },
        {
            name: "Noir",
            category: "monochrome",
            exposure: -0.1,
            contrast: 35,
            highlights: -20,
            shadows: -15,
            whites: 15,
            blacks: -20,
            temperature: -10,
            tint: 0,
            vibrance: -50,
            saturation: -80,
            grain: 15,
            grainGlobal: 1.3,
            bloomStrength: 15,
            bloomThreshold: 50,
            grainSize: 1.5,
            fade: 0,
            vignette: 30
        }
    ],

    // ============ CINEMA ============
    cinema: [
        {
            name: "Wes Anderson II",
            category: "cinema",
            exposure: 0.2,
            contrast: -10,
            highlights: 10,
            shadows: 25,
            whites: 5,
            blacks: 15,
            temperature: 5,
            tint: 5,
            vibrance: 30,
            saturation: 25,
            grain: 3,
            grainGlobal: 0.8,
            bloomStrength: 12,
            bloomThreshold: 65,
            grainSize: 0.8,
            fade: 10,
            hslYellow: [5,20,10],
            hslRed: [0,15,5],
            hslBlue: [0,25,10]
        },
        {
            name: "Blockbuster",
            category: "cinema",
            exposure: 0,
            contrast: 20,
            highlights: -15,
            shadows: 10,
            whites: 10,
            blacks: -5,
            temperature: 5,
            tint: 0,
            vibrance: 15,
            saturation: 10,
            grain: 8,
            grainGlobal: 1,
            bloomStrength: 20,
            bloomThreshold: 60,
            grainSize: 1.2,
            fade: 5
        },
        {
            name: "Blade Runner",
            category: "cinema",
            exposure: 0,
            contrast: 10,
            highlights: -20,
            shadows: 10,
            whites: -10,
            blacks: 10,
            temperature: -20,
            tint: 15,
            vibrance: 20,
            saturation: 5,
            grain: 10,
            grainGlobal: 1.1,
            bloomStrength: 40,
            bloomThreshold: 45,
            grainSize: 1.3,
            fade: 15
        },
        {
            name: "Wes Anderson",
            category: "cinema",
            exposure: 0.1,
            contrast: -5,
            highlights: -10,
            shadows: 15,
            whites: -5,
            blacks: 10,
            temperature: 15,
            tint: 10,
            vibrance: 25,
            saturation: 15,
            grain: 5,
            grainGlobal: 0.9,
            bloomStrength: 10,
            bloomThreshold: 65,
            grainSize: 0.9,
            fade: 5
        }
    ],

    // ============ EXPERIMENTAL ============
    experimental: [
        {
            name: "Teal & Orange",
            category: "experimental",
            exposure: 0.05,
            contrast: 15,
            highlights: -10,
            shadows: 5,
            whites: 5,
            blacks: 0,
            temperature: 10,
            tint: -5,
            vibrance: 10,
            saturation: 5,
            grain: 5,
            grainGlobal: 1,
            bloomStrength: 30,
            bloomThreshold: 60,
            grainSize: 1,
            fade: 3,
            hslAqua: [0,25,0],
            hslOrange: [0,20,5]
        },
        {
            name: "Teal & Orange II",
            category: "experimental",
            exposure: 0,
            contrast: 25,
            highlights: -15,
            shadows: -10,
            whites: 10,
            blacks: -5,
            temperature: 5,
            tint: -10,
            vibrance: 20,
            saturation: 15,
            grain: 8,
            grainGlobal: 1.1,
            bloomStrength: 25,
            bloomThreshold: 65,
            grainSize: 1.2,
            fade: 5,
            hslBlue: [-20,30,-10],
            hslOrange: [5,25,5],
            splitHighlightHue: 0.08,
            splitHighlightSat: 0.2,
            splitShadowHue: 0.55,
            splitShadowSat: 0.3
        },
        {
            name: "Matrix Green",
            category: "experimental",
            exposure: -0.05,
            contrast: 25,
            highlights: -15,
            shadows: 0,
            whites: 10,
            blacks: -10,
            temperature: -15,
            tint: -20,
            vibrance: -20,
            saturation: -30,
            grain: 8,
            grainGlobal: 1.2,
            bloomStrength: 35,
            bloomThreshold: 50,
            grainSize: 1.1,
            fade: 10,
            hslGreen: [0,40,10]
        },
        {
            name: "Glitch 99",
            category: "experimental",
            exposure: 0.1,
            contrast: 25,
            highlights: 10,
            shadows: -15,
            whites: 5,
            blacks: 15,
            temperature: -10,
            tint: 40,
            vibrance: 30,
            saturation: 10,
            grain: 25,
            grainSize: 1.5,
            bloomStrength: 30,
            bloomThreshold: 60
        },
        {
            name: "Disposable Flash",
            category: "experimental",
            exposure: 0.2,
            contrast: 30,
            highlights: 20,
            shadows: -10,
            whites: 15,
            blacks: -5,
            temperature: -5,
            tint: -5,
            vibrance: 10,
            saturation: 5,
            grain: 15,
            grainSize: 1.1,
            haloStrength: 0.5,
            chromaticAberration: 5,
            vignette: 40
        },
        {
            name: "Void",
            category: "experimental",
            exposure: -0.2,
            contrast: 10,
            highlights: -30,
            shadows: -30,
            whites: -20,
            blacks: -20,
            temperature: -20,
            tint: 0,
            vibrance: -50,
            saturation: -60,
            grain: 40,
            grainSize: 0.8,
            fade: 20
        },
        {
            name: "Glitch Pop",
            category: "experimental",
            exposure: 0.1,
            contrast: 30,
            highlights: 20,
            shadows: -15,
            whites: 25,
            blacks: -20,
            temperature: -25,
            tint: 35,
            vibrance: 50,
            saturation: 40,
            grain: 20,
            grainGlobal: 1.8,
            bloomStrength: 30,
            bloomThreshold: 45,
            grainSize: 2,
            fade: 0
        },
        {
            name: "Neon Noir",
            category: "experimental",
            exposure: -0.1,
            contrast: 40,
            highlights: -25,
            shadows: 20,
            whites: 20,
            blacks: -30,
            temperature: -35,
            tint: 40,
            vibrance: 40,
            saturation: 20,
            grain: 12,
            grainGlobal: 1.1,
            bloomStrength: 40,
            bloomThreshold: 40,
            grainSize: 1.4,
            fade: 0,
            vignette: 35
        },
        {
            name: "Acid Trip",
            category: "experimental",
            exposure: 0.2,
            contrast: -10,
            highlights: 25,
            shadows: 30,
            whites: 20,
            blacks: 25,
            temperature: -20,
            tint: 50,
            vibrance: 70,
            saturation: 60,
            grain: 5,
            grainGlobal: 1,
            bloomStrength: 50,
            bloomThreshold: 30,
            grainSize: 1,
            fade: 15
        },
        {
            name: "Thermal Vision",
            category: "experimental",
            exposure: 0.05,
            contrast: 35,
            highlights: 10,
            shadows: -20,
            whites: 15,
            blacks: -25,
            temperature: 50,
            tint: 20,
            vibrance: 60,
            saturation: 50,
            grain: 3,
            grainGlobal: 0.5,
            bloomStrength: 15,
            bloomThreshold: 60,
            grainSize: 0.8,
            fade: 0
        },
        {
            name: "Solar Flare",
            category: "experimental",
            exposure: 0.1,
            contrast: -10,
            highlights: -10,
            shadows: 20,
            whites: -10,
            blacks: 10,
            temperature: 30,
            tint: 10,
            vibrance: 20,
            saturation: 10,
            grain: 10,
            grainGlobal: 1.5,
            bloomStrength: 35,
            bloomThreshold: 50,
            lightLeak: 50,
            fade: 15
        },
        {
            name: "Azure Dream",
            category: "experimental",
            exposure: 0.05,
            contrast: -15,
            highlights: -20,
            shadows: 15,
            whites: -10,
            blacks: 5,
            temperature: -25,
            tint: 0,
            vibrance: 10,
            saturation: -10,
            grain: 5,
            grainGlobal: 1,
            bloomStrength: 50,
            bloomThreshold: 40,
            fade: 10
        },
        {
            name: "Candy Shop",
            category: "experimental",
            exposure: 0.1,
            contrast: 5,
            highlights: -10,
            shadows: 5,
            whites: 5,
            blacks: 0,
            temperature: -5,
            tint: 15,
            vibrance: 50,
            saturation: 20,
            grain: 0,
            bloomStrength: 25,
            bloomThreshold: 60,
            hslBlue: [-20,20,10],
            hslMagenta: [10,20,10]
        },
        {
            name: "Fade 2 Black",
            category: "experimental",
            exposure: -0.1,
            contrast: -20,
            highlights: -20,
            shadows: 10,
            whites: -40,
            blacks: 30,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -100,
            grain: 20,
            grainGlobal: 1.2,
            bloomStrength: 5,
            bloomThreshold: 80,
            fade: 40
        },
        {
            name: "Acid Green",
            category: "experimental",
            exposure: 0,
            contrast: 30,
            highlights: 10,
            shadows: -10,
            whites: 10,
            blacks: -10,
            temperature: -10,
            tint: 50,
            vibrance: -20,
            saturation: -40,
            grain: 25,
            grainGlobal: 1.6,
            bloomStrength: 30,
            bloomThreshold: 50,
            grainSize: 1,
            hslGreen: [0,50,0]
        },
        {
            name: "Bleach Bypass II",
            category: "experimental",
            exposure: -0.05,
            contrast: 50,
            highlights: 10,
            shadows: -20,
            whites: 10,
            blacks: -20,
            temperature: -5,
            tint: 0,
            vibrance: -40,
            saturation: -50,
            grain: 18,
            grainGlobal: 1.3,
            grainSize: 0.9,
            bloomStrength: 10,
            bloomThreshold: 70,
            clarity: 25
        },
        {
            name: "CCTV",
            category: "experimental",
            description: "Surveillance camera. Green tint, low fi.",
            exposure: 0.1,
            contrast: 10,
            highlights: -30,
            shadows: 20,
            whites: -20,
            blacks: 10,
            temperature: 0,
            tint: 40,
            vibrance: -80,
            saturation: -80,
            grain: 40,
            grainSize: 2,
            scanlineIntensity: 30,
            pixelateSize: 2,
            fade: 20
        },
        {
            name: "Night Vision",
            category: "experimental",
            description: "Green phosphor look.",
            exposure: 0.2,
            contrast: 50,
            highlights: 30,
            shadows: 0,
            whites: 30,
            blacks: 10,
            temperature: 0,
            tint: 50,
            vibrance: -100,
            saturation: -100,
            grain: 50,
            grainSize: 2,
            bloomStrength: 50,
            hslGreen: [0,0,0],
            splitHighlightHue: 120,
            splitHighlightSat: 100,
            splitShadowHue: 120,
            splitShadowSat: 100
        },
        {
            name: "Gameboy",
            category: "experimental",
            description: "4-shade green monochrome.",
            exposure: 0,
            contrast: 100,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: -100,
            saturation: -100,
            grain: 0,
            pixelateSize: 4,
            ditherStrength: 50,
            splitHighlightHue: 80,
            splitHighlightSat: 80,
            splitShadowHue: 140,
            splitShadowSat: 80
        },
        {
            name: "VGA",
            category: "experimental",
            description: "Crunchy 256 color look.",
            exposure: 0,
            contrast: 30,
            highlights: 10,
            shadows: -10,
            whites: 10,
            blacks: -10,
            temperature: 0,
            tint: 0,
            vibrance: 50,
            saturation: 30,
            grain: 0,
            pixelateSize: 2,
            ditherStrength: 30
        },
        {
            name: "Floppy Disk",
            category: "experimental",
            description: "Digital corruption.",
            exposure: 0,
            contrast: 20,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: 0,
            tint: 0,
            vibrance: 0,
            saturation: -20,
            grain: 10,
            glitchStrength: 40,
            pixelateSize: 3
        },
        {
            name: "Predator",
            category: "experimental",
            description: "Thermal vision heat map feel.",
            exposure: 0,
            contrast: 50,
            highlights: 20,
            shadows: -20,
            whites: 10,
            blacks: -10,
            vibrance: 100,
            saturation: 100,
            temperature: 50,
            tint: 50,
            splitHighlightHue: 0,
            splitHighlightSat: 80,
            splitShadowHue: 240,
            splitShadowSat: 80
        },
        {
            name: "Harman Phoenix 200",
            category: "experimental",
            description: "High contrast, strong grain, weird glows.",
            exposure: 0.05,
            contrast: 30,
            highlights: 15,
            shadows: 10,
            whites: 10,
            blacks: 5,
            temperature: 5,
            tint: 0,
            vibrance: 20,
            saturation: 25,
            grain: 20,
            grainGlobal: 1.2,
            bloomStrength: 30,
            bloomThreshold: 55
        },
        {
            name: "Matrix Green",
            category: "experimental",
            exposure: -0.2,
            contrast: 50,
            highlights: 40,
            shadows: -50,
            whites: 20,
            blacks: -10,
            temperature: -20,
            tint: -100,
            vibrance: 50,
            saturation: 0,
            posterize: 30,
            grain: 50,
            grainSize: 0.5,
            fade: 0
        },
        {
            name: "Heatmap",
            category: "experimental",
            exposure: 0,
            contrast: 100,
            highlights: 0,
            shadows: 0,
            whites: 0,
            blacks: 0,
            temperature: -100,
            tint: 0,
            vibrance: 50,
            saturation: 50,
            hslRed: [0,50,20],
            hslBlue: [0,50,0],
            bloomStrength: 30,
            posterize: 10,
            fade: 0
        },
        {
            name: "CGA Palette",
            category: "experimental",
            exposure: 0.2,
            contrast: 80,
            highlights: 20,
            shadows: -20,
            whites: 10,
            blacks: -10,
            temperature: 0,
            tint: 100,
            vibrance: 100,
            saturation: 100,
            hslGreen: [180,0,0],
            hslRed: [0,0,0],
            posterize: 4,
            fade: 0
        },
        {
            name: "Night Vision",
            category: "experimental",
            exposure: 0.5,
            contrast: 30,
            highlights: 50,
            shadows: 20,
            whites: 30,
            blacks: 0,
            temperature: -20,
            tint: -80,
            vibrance: -100,
            saturation: -100,
            bloomStrength: 60,
            bloomThreshold: 20,
            grain: 80,
            grainSize: 1,
            vignette: 80,
            fade: 10
        },
        {
            name: "Vaporwave",
            category: "experimental",
            exposure: 0.1,
            contrast: 10,
            highlights: 0,
            shadows: 20,
            whites: 0,
            blacks: 10,
            temperature: -30,
            tint: 50,
            vibrance: 40,
            saturation: 20,
            fade: 30,
            hue: 0,
            bloomStrength: 30,
            bloomThreshold: 60
        }
    ],

    // ============ MUSE ============
    muse: [
        {
            name: "Soft & Warm",
            category: "muse",
            contrast: 5,
            temperature: 8,
            clarity: -10,
            vibrance: 10,
            hsl: [
                { channel: "orange", lum: 5 },
                { channel: "yellow", sat: -10 }
            ],
            hidden: true
        }
    ],

};

/**
 * Get all presets as a flat array
 */
function getAllPresets() {
    const all = [];
    Object.keys(FilmPresets).forEach(category => {
        FilmPresets[category].forEach(preset => {
            all.push({ ...preset, category });
        });
    });
    return all;
}

/**
 * Get presets by category
 */
function getPresetsByCategory(category) {
    if (category === 'all') {
        return getAllPresets();
    }
    return FilmPresets[category] || [];
}

/**
 * Find preset by name
 */
function findPreset(name) {
    const all = getAllPresets();
    return all.find(p => p.name.toLowerCase() === name.toLowerCase());
}

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { FilmPresets, getAllPresets, getPresetsByCategory, findPreset };
}

// Browser global export
if (typeof window !== 'undefined') {
    window.FilmPresets = FilmPresets;
    window.getPresetsByCategory = getPresetsByCategory;
    window.getAllPresets = getAllPresets;
    window.findPreset = findPreset;
}
